# Site settings
title: Keksobooking
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Does anybody know how to add a backend to jekyll-based website? Thank you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://o0.github.io" # the base hostname & protocol for your site
twitter_username: iamo0
github_username:  o0

# Build settings
markdown: kramdown
