# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
description: > # this means to ignore newlines until "baseurl:"
email: alexeenko.igor@gmail.com
github_username:  o0
markdown: kramdown
title: Игорь Алексеенко
twitter_username: iamo0
url: "http://o0.github.io" # the base hostname & protocol for your site
