# Site settings
title: Игорь Алексеенко
email: alexeenko.igor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://o0.github.io" # the base hostname & protocol for your site
twitter_username: iamo0
github_username:  o0

# Build settings
markdown: kramdown
